### ISSUE TITLE
Transform in "add component" window doesn't seem to work 

### ISSUE THREAD

**Issue by rerpha** [ess-dmsc/nexus-constructor#112]
Seems to work OK in the components pane, but for some reason when adding a component and setting a translation via the sample it logs an exception and refuses to add the component. 

```
Traceback (most recent call last):
  File "nexus-constructor/nexus_constructor/qml_models/instrument_model.py", line 362, in get_transform_model
    return self.transform_models[index]
IndexError: list index out of range
```

**Comment by DominicOram** [comment]
May be fixed by https://github.com/ess-dmsc/nexus-constructor/issues/188
