### ISSUE TITLE
Match model colour with component listview

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/nexus-constructor#140]
Components' models in the 3D view should each have a different (randomly assigned?) colour. The same colour should be shown on that component in the listview, maybe as a small square or as the background colour for that item in the listview.

Alternatively we could display all components in the same colour but allow selecting a component in the listview somehow and highlighting this in the 3D view by changing only its colour.

**Comment by rerpha** [comment]
We should make sure we have an option to turn this off as well for accessibility reasons - it may become difficult for colourblind users to see/differentiate components.

**Comment by kmurica** [comment]
Also maybe find some inspiration in something like https://www.secretstache.com/blog/designing-for-color-blind-users/
