### ISSUE TITLE
Move away from QAbstractListModel

### ISSUE THREAD

**Issue by DominicOram** [ess-dmsc/nexus-constructor#153]
Most of the models inherit from QAbstractListModel and hold their properties as items within a list. This leads to:
* Some odd "magic numbers":
```
NameRole = Qt.UserRole + 1
DescriptionRole = Qt.UserRole + 2
TransformParentIndexRole = Qt.UserRole + 3
DependentTransformIndexRole = Qt.UserRole + 4
```
* Hard to understand logic for getting/setting the data
* Methods such as rowCount and roleNames, which are unclear to their purpose

This ticket is to:
* Find a more readable way to do this, maybe using [QObjects](https://doc.qt.io/qt-5/qobject.html)
* Document this pattern
* Add unit tests where appropriate
* Functionality of the program should generally not change

**Comment by rerpha** [comment]
PRs are in for geometry models and (all but one) pixel models. The one that isn't a QObject is still an abstract list but I think that's the appropriate type for it. 

I can't figure out how to use properties correctly with abstract list, there's not any documentation on whether we should be using roles for that or properties. 

I think the transform model should also stay as a list as it contains a list of transforms. Likewise with instrumentModel, which contains a list of the components.
