### ISSUE TITLE
Add/Edit Component Window should be passed the component to modify

### ISSUE THREAD

**Issue by DominicOram** [ess-dmsc/nexus-constructor#158]
Currently the whole instrument model is passed to the Add/Edit Component Window. Changes then go through this model, with an index describing which component should be edited. Instead this screen should be given a component object and deal with this as much as possible. This should lead to the following changes:
* Moving code such as set_pixel_model into the component objects
* Better sharing of QMl code between Add/Edit Component Window
* Additional unit tests where code has changed

**Comment by matthew-d-jones** [comment]
Blocked by #157

**Comment by matthew-d-jones** [comment]
This ticket is replaced by #322
