### ISSUE TITLE
Cannot add a rotated cylinder

### ISSUE THREAD

**Issue by DominicOram** [ess-dmsc/nexus-constructor#161]
When I create a cylinder and give it a different axis to be aligned upon it does not rotate to this axis. This is because when the axis is set in the setData method of the geometry model it does not call setX/setY/setZ on the QVector3D, instead it tries to set an x/y/z attribute, which doesn't exist. Moving away from the pattern in https://github.com/ess-dmsc/nexus-constructor/issues/153 will make this easier to fix.

**Comment by rerpha** [comment]
I believe since #190 has been merged this is now fixed?

**Comment by DominicOram** [comment]
Yes, fixed.
