### ISSUE TITLE
Some other useful QML-related things to add to the wiki

### ISSUE THREAD

**Issue by DolicaAkelloEgwel** [ess-dmsc/nexus-constructor#171]
- functions
- Singletons and `qmldir` for creating variables that can be shared across files
- Row/ColumnLayout
- aliases
- Explanation of the purpose of the custom types: `LabeledTextField` and `ActiveScrollBar` (more for dev notes rather than the QML tutorial bit)
- QVariant
- anchors

@rerpha @DominicOram Do you think these should all be in the wiki or is some of it not needed? Also what else would be useful?

**Comment by rerpha** [comment]
Definitely should be in the wiki, I think we should jot down all we know about QML :+1:

**Comment by rerpha** [comment]
- [ ] functions
- [ ] singletons and qmldir
- [ ] row/columnlayout
- [ ] aliases
- [ ] Explanation of the purpose of the custom types: LabeledTextField and ActiveScrollBar (more for dev notes rather than the QML tutorial bit)
- [ ] QVariant
- [ ] anchors

**Comment by rerpha** [comment]
closing this as we are switching to widgets.
