### ISSUE TITLE
Allow user to change size of initial beam/sample

### ISSUE THREAD

**Issue by DolicaAkelloEgwel** [ess-dmsc/nexus-constructor#173]
Tobias mentioned it would be good to be able to change the beamline and sample size as well as the components. 

We use this opportunity to remove any hardcoded OFF geometry in the program.

**Comment by matthew-d-jones** [comment]
The default beam diameter and sample size should also be reduced to something vaguely realistic. We may have to remove the beam altogether, or at least allow it to be switched off, but that would be a separate ticket.

**Comment by rerpha** [comment]
Closing this for now, we have moved the beam into the gnomon axes. #346
