### ISSUE TITLE
Failure to parse numeric values with decimals

### ISSUE THREAD

**Issue by SkyToGround** [ess-dmsc/nexus-constructor#219]
It appears that the widgets that parse numeric values can not properly handle decimal values on machines that are not set to use English language settings.
E.g. the application properly determines that the "," character is the decimal delimiter used in the Swedish language. However, the string ``"12.12"`` is turned into the numeric value ``12``.

Alternative 1: Remove support for international representation of numeric values.
Alternative 2: Fix international representation of numeric values.

**Comment by rerpha** [comment]
https://www.qtcentre.org/threads/63501-comma-as-decimal-seperator

**Comment by kmurica** [comment]
I believe alternative 2 would be quite easy to fix for this issue.
