### ISSUE TITLE
Rendering issue caused by hiding JSON view

### ISSUE THREAD

**Issue by SkyToGround** [ess-dmsc/nexus-constructor#221]
Re-production steps:
1. Disable the JSON view.
2. Minimise window.
3. Re-enable JSON view.

Fix alternative 1:
Change minimum width of 3D view when switching off/on the JSON view.

Fix alternative 2:
Change window size (if required) when switching on JSON view.

**Comment by matthew-d-jones** [comment]
This is not observable on Linux (or at least on Ubuntu KDE 18.04).

**Comment by SkyToGround** [comment]
@matthew-d-jones I was maybe not very clear in my re-production steps. Step 2 should be: resize the window to its minimum width.

**Comment by matthew-d-jones** [comment]
I don't notice anything wrong in the window when I do that, but I do get a couple of these in the console:
```
QOpenGLFramebufferObject: Framebuffer incomplete attachment.
```
