### ISSUE TITLE
Add way of changing unit of file

### ISSUE THREAD

**Issue by SkyToGround** [ess-dmsc/nexus-constructor#223]
When selecting a 3d model file, you are prompted to select a unit. It appears that it is currently not possible to change the selected unit without re-selecting the file. It should be.

**Comment by rerpha** [comment]
I agree, this should be consistent with the cylinder type.

**Comment by rerpha** [comment]
Will be fixed for the widgets stuff in #307

**Comment by rerpha** [comment]
Closed in #307
