### ISSUE TITLE
Unit in cylinder component "Full editor" is ignored

### ISSUE THREAD

**Issue by SkyToGround** [ess-dmsc/nexus-constructor#224]
It is not possible to set this to anything other than "m". When re-opening the editor, the value (unit) is reset to "m".

**Comment by matthew-d-jones** [comment]
I suspect the units are only being used when a CAD file is loaded. We'll need to store them in the model so that the setting persists.

**Comment by matthew-d-jones** [comment]
This turns out to be non-trivial to solve in a nice way, due to QML. As we are planning to move to widgets we should revisit this ticket once that is complete.

**Comment by rerpha** [comment]
Closing this as it only affects the QML code. 

This should be sorted out in #322 as that should just use the "add component" window in which the units line edit can be edited before or after adding the geometry info.
