### ISSUE TITLE
Put the menu bar where it belongs on MacOSX

### ISSUE THREAD

**Issue by SkyToGround** [ess-dmsc/nexus-constructor#227]
Having the menu bar in the window is not best practice on MacOSX. It should instead be in the standard (for MacOSX) location of the (permanent) menu bar along the upper edge of the screen.

**Comment by rerpha** [comment]
@SkyToGround Not sure we can do this on Pyside2 because we don't have Qt::AA_DontUseNativeMenuBar

**Comment by rerpha** [comment]
Closing, this is the case for widgets applications by default.
