### ISSUE TITLE
File dialog when using KDE does not warn about overwriting exisiting file

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/nexus-constructor#259]
To reproduce the problem:
Choose File->Export to NeXus File
and save a file.
Add another component, then save to the same file name. On KDE no error is reported and the file is overwritten.
Doesn't seem to be the case on WIndows, Mac OS or Linux with Gnome environment.

**Comment by rerpha** [comment]
Fixed in widgets, using qt dialog rather than native.
