### ISSUE TITLE
Transformation values disappear when moving up or down 

### ISSUE THREAD

**Issue by rerpha** [ess-dmsc/nexus-constructor#266]
The transformation values of a component seem to disappear when being moved up/down in order. The transformation that moves upwards or downwards seems to be affected but not the one that is moved secondarily.

**Comment by DolicaAkelloEgwel** [comment]
It looks like this is related to #264 and is no longer a problem?

**Comment by rerpha** [comment]
> It looks like this is related to #264 and is no longer a problem?

cool, go ahead and close both issues if it's been fixed

**Comment by DolicaAkelloEgwel** [comment]
The problem seems to have disappeared.
