### ISSUE TITLE
Widgets: fix component list

### ISSUE THREAD

**Issue by rerpha** [ess-dmsc/nexus-constructor#296]
Branch this feature off of `switch_to_widgets` and create pull requests to merge against this branch. 

Fix component list with the new widgets on the branch `switch_to_widgets` 

This should be doable as the instrument model is a QAbstractListModel so the listview should work.

**Comment by matthew-d-jones** [comment]
@SkyToGround Has a prototype for this.

**Comment by matthew-d-jones** [comment]
Closed by #360
