### ISSUE TITLE
Widgets: fix exporting to filewriter JSON 

### ISSUE THREAD

**Issue by rerpha** [ess-dmsc/nexus-constructor#299]
Branch this feature off of `switch_to_widgets` and create pull requests to merge against this branch. 

Currently does nothing, the functionality is there already in python but needs to be linked with the UI.

**Comment by matthew-d-jones** [comment]
No longer requires a model, clicking export to JSON should do a one off generation of the JSON rather than updating a model every time anything changes (which has proven to be a major bottleneck in the application).
