### ISSUE TITLE
Widgets: add transformation controls

### ISSUE THREAD

**Issue by rerpha** [ess-dmsc/nexus-constructor#310]
Add transformation controls and put them in the nexus file. this relies on the add component window being merged, see #307

**Comment by matthew-d-jones** [comment]
We should decide whether these should be in the add component interface or only in the component list in the main window, because in the component interface you can't see the 3D view to check you are getting them correct.

**Comment by rerpha** [comment]
blocked by #296 if we are only having it in the component list

**Comment by rerpha** [comment]
We have controls now in the component view, we just need to plumb them into the instrument view. Ticket for this is #326
