### ISSUE TITLE
Widgets: stop taking ownership of list for list view, and use nexus entirely for model

### ISSUE THREAD

**Issue by rerpha** [ess-dmsc/nexus-constructor#311]
Currently the `NeXusWrapper` has ownership of an `InstrumentModel` which is essentially just a Qt list that contains all the components. My suggestion is that we don't take ownership of this, and instead generate it when needs be from the Nexus file itself. 

there is already a `get_components_list` function in `NexusWrapper` so the interface will not have to be changed even if people are working on stuff that relies on the component list so long as they use this method to access it.

**Comment by matthew-d-jones** [comment]
Closed by #337
