### ISSUE TITLE
Use qtpy wrapper

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/nexus-constructor#315]
qt3d bindings were added to `qtpy` yesterday and are already available in release 1.8.0 through pip: https://pypi.org/project/QtPy/
`qtpy` is a wrapper over "Qt for Python" (pyside2) _and pyqt5, giving both of them the pyside2 interface. In other words it would be trivial for us to start using it and would allow us to switch out pyside2 for pyqt5 without any code changes at a future time. This would allow interop/integration with Nicos later if needed.

**Comment by rerpha** [comment]
Looks like qtpy has it's own UIC so we should be able to do use this to convert our .ui files and generate the python layout files from them.
