### ISSUE TITLE
Use transformations in 3D view

### ISSUE THREAD

**Issue by DolicaAkelloEgwel** [ess-dmsc/nexus-constructor#326]
When the 3D view gets the shape of each component it also needs to get the full "depends on" chain of transformations so that it can render the component at the correct position and orientation.

Not sure if it is already possible to get the full "depends on" chain, possibly only transformations local to a component?

**Comment by rerpha** [comment]
blocked by #296

**Comment by rerpha** [comment]
I think this is done.
