### ISSUE TITLE
Add field dialog for links in HDF file

### ISSUE THREAD

**Issue by rerpha** [ess-dmsc/nexus-constructor#330]
Add a dialog for adding HDF links to a component when a user selects the link type in the fields list.
The line edit should have autocomplete for any dataset or group in the file. See the name field for how to enable autocompletion. h5py `visititems()` could be used to traverse the whole nexus file structure and record all paths to use for the autocompletion.

**Comment by matthew-d-jones** [comment]
Having a text field entry for the path is good enough as the first step for this ticket, but I've made another ticket to add "browse" button functionality: #391
