### ISSUE TITLE
Deal with units in Transformation

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/nexus-constructor#339]
Add a units getter and setter (`@property`) to `Transformation`.
A `get_si_value` is probably a good idea for use by the 3D view. This would use the `units` to convert value to SI units with the `pint` library.

**Comment by zjttoefs** [comment]
Are you sure? The SI unit for angle is radian.

**Comment by matthew-d-jones** [comment]
@zjttoefs Yes, this would be for the 3D view to calculate where to display things, not for how the transformation's numerical value is displayed to the user.

**Comment by rerpha** [comment]
This should be much easier once #632 is merged as it adds the unit field to transformation along with a convenient way to edit it

**Comment by rerpha** [comment]
`units` are now in the transformation class so this should just be a case of tying them up with the transformation magnitude.

**Comment by umithardal** [comment]
The description is unclear. The tickets needs a second look.
