### ISSUE TITLE
Widgets: write filewriter json from nexus file rather than instrumentmodel

### ISSUE THREAD

**Issue by rerpha** [ess-dmsc/nexus-constructor#341]
We need to generate the filewriter JSON commands from the nexus file itself rather than the current method of using the contents of `InstrumentModel`. As this class is being deprecated and removed, we should use the nexus file as the starting point to generate the JSON instead. 

Matt potentially has some code that will generate the fw JSON from the in-memory nexus file.

**Comment by matthew-d-jones** [comment]
Copy code from https://github.com/ess-dmsc/nexus-json. Don't import it in requirements file as we will need to change the code to deal with Kafka streams etc later.

For now use it to generate the json directly from the in-memory file and replace the test in test_json.py.
