### ISSUE TITLE
Output forwarder command message

### ISSUE THREAD

**Issue by rerpha** [ess-dmsc/nexus-constructor#361]
We should add a way to output a forwarder command message by looking through Kafka stream fields and selecting all components that are marked with `f142` as the schema.

**Comment by matthew-d-jones** [comment]
blocked by #329

**Comment by rerpha** [comment]
Thinking about this, does the f142 schema actually contain a PV name/channel? if not we will need to add this to the nexus file and create a dialog for it

**Comment by matthew-d-jones** [comment]
The "source" field in f142 is the PV name.
