### ISSUE TITLE
Add tests for Ok_validator in `validators.py`

### ISSUE THREAD

**Issue by rerpha** [ess-dmsc/nexus-constructor#368]
Would be nice to test the OK button validator. Could use a dummy/mock for the buttons passed into it that either return true or false when `isChecked()` is called.

**Comment by rerpha** [comment]
I have tested other validators in this file in #359 but the OK_validator is not covered yet.

**Comment by DolicaAkelloEgwel** [comment]
Accidentally referenced issue 386 rather than 368 in the pull request...
