### ISSUE TITLE
Gnomon is swallowed by the sample cube if you zoom in enough

### ISSUE THREAD

**Issue by DolicaAkelloEgwel** [ess-dmsc/nexus-constructor#386]
This is noticeable if you press Esc.

**Comment by rerpha** [comment]
Can we move the gnomon in front of everything?

**Comment by DolicaAkelloEgwel** [comment]
There is an example for it here https://stackoverflow.com/questions/51818584/2d-meshes-in-qt3d/51839858#51839858

I think the code that managed it was once there but was removed by mistake because it appeared to do nothing.
