### ISSUE TITLE
Allow multiple cylinders when defining and loading cylindrical geometries

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/nexus-constructor#398]
The NeXus standard for [NXcylindrical_geometry](http://download.nexusformat.org/sphinx/classes/base_classes/NXcylindrical_geometry.html) supports multiple cylinders in the same group.

Currently when loading from file, all cylinders except the first one are ignored. This is documented in a unit test in `test_cylindrical_geometry.py`.
Also, it is currently only possible to create a single cylinder when defining cylindrical geometries in the GUI.

**Comment by kmurica** [comment]
Maybe break this issue up in two separate tickets/issues?
Suggestion for 2 tickets/issues:
1. Fix so that when user loads from file all cylinders are loaded correctly and not only the first one.
2. Make it possible to create multiple cylinders when defining cylindrical geometries in the GUI.
