### ISSUE TITLE
Look into using an undo/redo stack to revert changes in the model

### ISSUE THREAD

**Issue by ACLay** [ess-dmsc/nexus-constructor#40]
Should allow live updates to the model, which can be reflected in a visualisation, while still allowing changes to be undone.

**Comment by matthew-d-jones** [comment]
https://doc.qt.io/qtforpython/PySide2/QtWidgets/QUndoCommand.html

**Comment by rerpha** [comment]
- Do we still want this?
- Is it possible using widgets?
