### ISSUE TITLE
Support 3D and higher dimensional arrays in fields

### ISSUE THREAD

**Issue by rerpha** [ess-dmsc/nexus-constructor#405]
~Blocked by #401~

Currently we only support two-dimensional arrays when adding fields. We should do something like hdfview with multiple pages for each dimension of the list.

**Comment by kmurica** [comment]
https://www.hdfgroup.org/downloads/hdfview/ and https://support.hdfgroup.org/products/java/hdfview/UsersGuide/ug05spreadsheet.html#ug05display might be a relevant link for this issue as HDFView is referenced.

`5.2.3 Three or More Dimensions
For a three or more dimensional dataset, the first two dimensions are displayed as a 2-D spreadsheet, and the third dimension is chosen as the page number of the 2-D spreadsheet, i.e. dim[0]=height, dim[1]=width and dim[2]=depth by default. Using the “Open As” option to change the default order of dimensions, the user can flip the page forward or backward to look at the 2D data values at different positions along the third dimension. The current page number is displayed in the status bar of the HDFView.

To flip a data sheet of a 3-D dataset, use the “First”, “Previous”, “Next” or “Last” command on the tool bar.

The following figure shows how a 4-D integer dataset of size 5 x 4 x 3 x 2 is displayed. The data is displayed in a spreadsheet of 5 X 4 (dim0 by dim1), of page 2 (dim2), cutting locations 2 at dim3.`
