### ISSUE TITLE
Improve UI when editing floats in array fields

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/nexus-constructor#412]
The behaviour when editing floats in an array field table is awkward, for example try typing `1.2` and you get `1.0.2`.

**Comment by rerpha** [comment]
I think this is to do with the way we are updating the model and view every time the text is changed (not finished editing).

we have a couple of options here that i can think of:
- implement a "done editing" button
- revert to having to finish the text editing (lose focus, press enter/tab) 
- inherit from QLineEdit and create a line edit with our own signals? but this seems a bit overkill.

**Comment by matthew-d-jones** [comment]
I think the model update on every change was only added to avoid losing data when the window is closed without deselecting the current cell. Perhaps the window close method can do the equivalent of a "done editing" button? Having a "done editing" button as well may not be a bad idea.

**Comment by matthew-d-jones** [comment]
Closed by #448
