### ISSUE TITLE
Remove red cube if there is no sample or if the sample has a shape

### ISSUE THREAD

**Issue by rerpha** [ess-dmsc/nexus-constructor#413]
Currently even if a sample is removed and a file is loaded in the red cube which indicates a sample is still displayed. It is hardcoded in and has nothing to do with the model, which is an issue. It should be related to the default sample in the h5py file and if removed should not be displayed.

**Comment by rerpha** [comment]
Check this is done before closing

**Comment by matthew-d-jones** [comment]
This is working. It retains the red, low opacity, material and renders whatever the shape of the sample is.
