### ISSUE TITLE
I think you can add  Software interface in README.md

### ISSUE THREAD

**Issue by 625781186** [ess-dmsc/nexus-constructor#416]

**Comment by rerpha** [comment]
Could you elaborate? Not sure quite what you mean?

**Comment by 625781186** [comment]
> Could you elaborate? Not sure quite what you mean?

Sorry.
I think, 
In the introduction, there is a software interface so that people can quickly understand the interface of the software.
like this : 
![image](https://user-images.githubusercontent.com/30521429/61884501-eb25f300-af2e-11e9-855e-d9c7a2d6d34b.png)
