### ISSUE TITLE
Pixel Controls: Allow Pixel Grid to store units

### ISSUE THREAD

**Issue by DolicaAkelloEgwel** [ess-dmsc/nexus-constructor#425]
"Row height" and "Column width" should have associated fields to specify the units. Currently they must be entered in metres (but there is no indication in the interface that they are in metres).

**Comment by umithardal** [comment]
@matthew-d-jones will investigate it.

**Comment by matthew-d-jones** [comment]
> @matthew-d-jones will investigate it.

I've updated the ticket description
