### ISSUE TITLE
Pixel Controls: Allow NXcylindrical_geometry to store multiple cylinders

### ISSUE THREAD

**Issue by DolicaAkelloEgwel** [ess-dmsc/nexus-constructor#429]
At the present it can only store a single cylinder. Allowing it to store multiple cylinders would enable users to record more detailed `detector_number` information.

Also once this is setup the `test_UI_GIVEN_increasing_cylinder_count_WHEN_user_chooses_pixel_mapping_THEN_pixel_mapping_list_is_regenerated` test can be un-xfailed.

**Comment by umithardal** [comment]
This is a duplicate.
