### ISSUE TITLE
Display pixel grids in 3D view

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/nexus-constructor#434]
For an NXdetector with a pixel grid defined, the 3D view should show each pixel in the grid. Currently it only displays the single pixel shape.

The 3D view will need to display the same pixel shape at different positions by constructing a translation for each pixel from the pixel offsets.

The `Component` methods `get_shape` and `remove_shape` will need to be updated. I think subclassing `Component` for components with single-pixel shape descriptions and then overriding this method and making use of polymorphism is probably the best approach.

**Comment by rerpha** [comment]
from what i can gather its cheaper to create one instance of a mesh and use it several times in different entities - like so https://stackoverflow.com/questions/48121630/an-efficient-way-to-render-similar-objects-in-qt3d
