### ISSUE TITLE
Entering a single column in array editor should result in a 1D dataset

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/nexus-constructor#438]
In the Add Component window adding an array field with a single column should result in a 1D dataset in the in-memory NeXus file. It currently gives an `N x 1` 2D dataset:
![Screenshot_20190819_105749](https://user-images.githubusercontent.com/13455433/63257318-68642f80-c271-11e9-96c4-c8964109e86b.png)

**Comment by rerpha** [comment]
We should investigate whether this is silx playing up or if it's actually doing this in the nexus file.

**Comment by rerpha** [comment]
it isn't silxes fault, we could use np.squeeze to stop this from happening.

**Comment by rerpha** [comment]
closed in #456
