### ISSUE TITLE
Use Black for formatting

### ISSUE THREAD

**Issue by mattclarke** [ess-dmsc/nexus-constructor#44]
https://black.readthedocs.io/en/stable/

Black is becoming quite popular in the Python world as a no holds barred formatter.
I propose we use that as it saves time formatting code and we don't need to discuss PEP8 conformance.

Perhaps it can be added as a git pre-commit hook?

**Comment by ACLay** [comment]
Looks usefull, though we're currently targeting python 3.5, which is used on our jenkins build nodes, and Black requires 3.6, so if we go with this that'll need to change.

**Comment by mattclarke** [comment]
You don't need it on the build server. You just run it locally before you commit.
