### ISSUE TITLE
Show components in 3D on load

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/nexus-constructor#442]
Implemented already? branch, pr?

Should be covered by #434 and #326.

**Comment by rerpha** [comment]
This did work but it looks like it has since broken, looks like the addition of pixel data has caused it as there are now two shape description groups(`shape` and `pixel_shape`) - we need to check both of these in the `get_shape` method in `component.py`

**Comment by rerpha** [comment]
works fine now.
