### ISSUE TITLE
Control over placeholder geometry for sample, monitor

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/nexus-constructor#443]
Rod? or common sample shapes?

**Comment by kmurica** [comment]
@matthew-d-jones could you add additional information in the description of this issue? Not 100 % sure if I understand it.

**Comment by matthew-d-jones** [comment]
Sorry this is a particularly badly written ticket. When a component is added and no explicit shape is defined for it then it is rendered as a cube ("placeholder shape") in the 3D view so that its position can be seen. I think there was a suggestion to allow different shapes to be used as placeholders but I don't think it was well thought through. There is another ticket to display the currently selected component in a different colour which seems like a better way to distinguish the components in the 3D view.
I will close this ticket, if it turns out to be important then the idea will resurface.
