### ISSUE TITLE
Improve performance of 3D view for many pixels

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/nexus-constructor#478]
Performance seems to be fine up to around 20,000 pixels on my machine, but it does not scale linearly and rapidly becomes unusable above that.

A few things to consider:
- instanced rendering (QML example: https://github.com/GarageGames/Qt/tree/master/qt-5/qt3d/examples/qt3d/bigscene-instanced-qml). I spent some time looking into this and it is not obvious if it is possible via the Python API.
- combine pixels into a single entity per detector, helps if the problem is too many entities but doesn't help if the rendering process is the bottleneck.
- specific optimisations, for example detecting the case of end-to-end cylinders (tube detectors) and rendering as a single cylinder. Mantid's Instrument View does this.
- render a rough shape for the whole panel rather than rendering every individual pixel somehow?

**Comment by DominicOram** [comment]
There seems to be two bottlenecks here:

* When adding the material to the entity. You can see this by comparing the time taken to add for example the gnomon:
```
Creating entity: 5.400000000044258e-06 
Adding comp <PySide2.Qt3DExtras.Qt3DExtras.QCylinderMesh object at 0x0000015B5FD8EB48>: 6.800000000084516e-06
Adding comp <PySide2.Qt3DExtras.Qt3DExtras.QPhongAlphaMaterial object at 0x0000015B5FD96108>: 5.2999999999858716e-06
Adding comp <PySide2.Qt3DCore.Qt3DCore.QTransform object at 0x0000015B5FD8E888>: 5.300000000096894e-06
```
to that of adding something from the file:
```
Creating entity: 3.7000000077114237e-06 
Adding comp <nexus_constructor.off_renderer.OffMesh object at 0x0000015B6DD93508>: 3.4999999911633495e-06
Adding comp <PySide2.Qt3DExtras.Qt3DExtras.QPhongAlphaMaterial object at 0x0000015B5FD96948>: 0.00021510000001967455
Adding comp <PySide2.Qt3DCore.Qt3DCore.QTransform object at 0x0000015B6F25F188>: 6.100000007336348e-06
```
* Setting the parent for all the entities takes ~3 seconds for them all

**Comment by DominicOram** [comment]
By creating a new material, just for the component I can bring the time down a little. Time taken with existing material:

```
Setting parent: 3.3599037999999997
Full added component: 4.781418200000001
INFO:root:Qt mesh built
Setting parent: 3.012792299999999
Full added component: 3.5747183999999983
```

Time taken with new material:
```
Setting parent: 2.3309780999999994
Full added component: 2.4645175000000004
INFO:root:Qt mesh built
Setting parent: 2.7188096
Full added component: 3.6131337000000006
```
