### ISSUE TITLE
Bug in outputting streams and links to File Writer JSON

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/nexus-constructor#481]
We store a `stream` field as a group in the in-memory NeXus file, but it should only result in a `stream` object in the JSON output, not a group containing a stream. In other words, there is an extra nested group in the JSON output which should not be there.

I think part of the confusion is that there is an edit box for a name when you add a stream to the field dialog. I don't think that should be there, instead we should make the field identifiable by displaying the topic (and maybe source if that exists) as a text label instead.

The `name` field of link objects in the JSON should be the name, not the full path from the root of the file.

**Comment by rerpha** [comment]
Links are also stored as a group which contain a link group. It should also only be written as a link object.
