### ISSUE TITLE
Windows: It is not obvious which component has been selected

### ISSUE THREAD

**Issue by DominicOram** [ess-dmsc/nexus-constructor#495]
On windows, if I click on a component in the component tree the edit/delete buttons become enabled but there is no indication which component has been selected, in the example below `select_me` has actually been selected:

![image](https://user-images.githubusercontent.com/10086797/67509456-f2be7a80-f68a-11e9-9586-0cb929b37a5a.png)

**Comment by rerpha** [comment]
no idea how to fix this to be honest. I have tried setting custom stylesheets, adding conditionals in the paint() method of ComponentEditorDelegate, setting mouse tracking on the treeview itself, but nothing has worked.

**Comment by rerpha** [comment]
Have found a fix for this. Will push as soon as I have Internet.
