### ISSUE TITLE
Use a view for the add/edit component window

### ISSUE THREAD

**Issue by rerpha** [ess-dmsc/nexus-constructor#496]
Copy the existing group if editing, and use a view on the copied group. if the ok button is pressed, replace the old group with the new one that was copied into the view. If the window is closed without the user pressing the ok button, the copied group can be thrown away and the file should stay the same. 

This means behaviour is the same for adding and editing a component.

**Comment by kmurica** [comment]
Relevant issue is https://github.com/ess-dmsc/nexus-constructor/issues/717 for this issue as well?
