### ISSUE TITLE
Remove buffer size options from ev42 stream options and add source

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/nexus-constructor#497]
The following options are no longer implemented in the file writer `ev42` writer module:
- `nexus.buffer.size_mb`
- `nexus.buffer.size_kb`
- `nexus.buffer.packet_max_kb`

**Comment by rerpha** [comment]
Whilst doing this, source should be added.

**Comment by rerpha** [comment]
May be easiest to do this in #471 as there are a lot of changes that can be cut down because of these fields no longer being required.

**Comment by rerpha** [comment]
now done in #471
