### ISSUE TITLE
Load V20 JSON file

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/nexus-constructor#498]
V20 JSON files for testing with are on the network drive:
```
smb://olympic/Babylon5/Public/Matthew Jones/V20_no_detector.json
smb://olympic/Babylon5/Public/Matthew Jones/V20_file_write_start.json
```

Current status:
- ~The file with no detector loads but there are problems with the transformations, for example choppers seem to be given the Lin1 component as a transformation.~
- ~The file with the detector gets stuck with high CPU use, I've left it for a few minutes with no change. Detector is 300x300 pixels which shouldn't be any problem.~

**Comment by rerpha** [comment]
when this is loading properly lets create a bug fix release.

**Comment by rerpha** [comment]
works with forwarder commands - successfully generated a forwarder command from the JSON

**Comment by rerpha** [comment]
some issues i've had: 

pixel data does not get added to 3d view on file load - #527 
components are not editable and currently result in exceptions being thrown to do with not having a group - #532

**Comment by rerpha** [comment]
Ok, it all seems to work so long as you edit the detector and give it a valid local file to load. I am going to close this seeing as #522 is nearly finished and completes this.
