### ISSUE TITLE
Update the manual test script

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/nexus-constructor#508]
Now the switch to widgets is complete the manual test script is out-of-date.

**Comment by kmurica** [comment]
@matthew-d-jones Could you point to the out-of-date manual test script in this issue? Not really sure which one this refers to. Thanks.

**Comment by matthew-d-jones** [comment]
https://github.com/ess-dmsc/nexus-constructor/blob/main/tests/UITests.md
it is linked from here: https://github.com/ess-dmsc/nexus-constructor/wiki/Developer-Notes#testing-the-ui
