### ISSUE TITLE
Cloning of submodules required for running the nexus-constructor

### ISSUE THREAD

**Issue by SkyToGround** [ess-dmsc/nexus-constructor#548]
It appears that for running the *nexus-constructor* (after cloning it from GitHub), it is required that you also clone the submodules (i.e. `git submodule update --init`). It is my opinion that this is not ok. If there is no other better way of solving this issue, I think copying the required files into the *nexus-constructor* repository is acceptable.

**Comment by rerpha** [comment]
I think it should be good enough just running subprocess.call, i will finish this later.

**Comment by matthew-d-jones** [comment]
Maybe git-subtree is an acceptable solution, it is what I should have used in the first place.
https://www.atlassian.com/git/tutorials/git-subtree
