### ISSUE TITLE
Remove chunk settings code (and related cruft)

### ISSUE THREAD

**Issue by SkyToGround** [ess-dmsc/nexus-constructor#550]
We are re-writing the file-writer to not use nested structures for its component settings. For example for setting the chunk size and and log interval. Hence we need to remove this part of the code from the nexus-constructor as well. This should also fix a few bugs for us.

**Comment by rerpha** [comment]
Marking as blocked as this has not yet been implemented in the filewriter. Once it has been implemented and the documentation for the commands have been updated this can be done.

**Comment by rerpha** [comment]
the code in #599 can be removed when this has been done

**Comment by rerpha** [comment]
Is there a jira ticket @SkyToGround ? or has it already been done?

**Comment by SkyToGround** [comment]
@rerpha I do know that there is a JIRA issue for fixing this in the file-writer but I do not remember the state of it. I do not remember the state of this in the nexus-constructor either. I also do not feel I have time to look at it right now. Hence, I suggest we leave this ticket as is and I will get back to this after we are done with the re-write of the file-writer. Unless you want to work on it of course.

**Comment by rerpha** [comment]
Found it: [DM-1719](https://jira.esss.lu.se/browse/DM-1719)

**Comment by rerpha** [comment]
Closing, the filewriter already uses dot notation instead of nested groups, the ticket is just for updating the fw docs to reflect this.
