### ISSUE TITLE
Single component visualisation in Edit Component Window

### ISSUE THREAD

**Issue by ACLay** [ess-dmsc/nexus-constructor#56]
Being able to view the current component would be useful for knowing details have been entered correctly, and I feel essential for a useful face number to pixel id mapping interface.
However, due to a bug/bugs in Qt3D, it's not currently possible to have Scene3D instances in child windows.

Examples that seem to match my experiences trying to add a Scene3D to the editor window can be found in the Qt bug tracker at: 
- https://bugreports.qt.io/browse/QTBUG-69877
- https://bugreports.qt.io/browse/QTBUG-64974
- https://bugreports.qt.io/browse/QTBUG-70747

Some of these have linked code, one currently due to release with Qt 5.11.3, and Qt 5.12.0, so we should wait for the next release before tackling this issue

**Comment by rerpha** [comment]
I suspect this is no longer an issue, technically the web view now uses an openGL context, and that is in a child window/dialog. I think this should be doable, perhaps we should put the 3d view as a pane in the geometry file dialog.

**Comment by rerpha** [comment]
if we are going to do this we should keep in mind the solution in #432 as it may happen again to this and crash the program when closing the add component window.
