### ISSUE TITLE
Advanced options do not get filled in when loading a JSON file

### ISSUE THREAD

**Issue by rerpha** [ess-dmsc/nexus-constructor#564]
This may be fixed by #550 because these may get un-nested and start working anyway. 

I think the reason they are not being filled in is because the fields are not getting separated by "."s - for example `nexus.nexus.indices_per_mb` does not get loaded into the in-memory nexus file.

**Comment by matthew-d-jones** [comment]
JSON loading is being reimplemented in a totally different way in model change. Closing ticket.
