### ISSUE TITLE
Can't seem to edit components with 1D array fields

### ISSUE THREAD

**Issue by DolicaAkelloEgwel** [ess-dmsc/nexus-constructor#580]
```
Traceback (most recent call last):
  File "/home/dolica/nexus-constructor/nexus_constructor/array_dataset_table_widget.py", line 128, in data
    value = self.array[index.row()][index.column()]
IndexError: invalid index to scalar variable.
```

**Comment by matthew-d-jones** [comment]
@DolicaAkelloEgwel can you give any more details on how to reproduce this?

On `master` I am able to create a component with an array field with type double, then edit the component and edit array values with no problem.

**Comment by DolicaAkelloEgwel** [comment]
I think it might be a problem specifically with 1D arrays...

**Comment by matthew-d-jones** [comment]
Ah yes, thank you. The error is displayed when the "Edit" button is clicked on a field with a 1D array value, and the array editor interface is not populated with the array values.
