### ISSUE TITLE
Status indicator for long running tasks

### ISSUE THREAD

**Issue by ACLay** [ess-dmsc/nexus-constructor#60]
File loading, mesh generation, json updating can all take a while with large files. Some indicator of what's going on would be useful.

**Comment by matthew-d-jones** [comment]
For example https://doc.qt.io/qt-5/qml-qtquick-controls2-busyindicator.html
Investigate other options too though.

**Comment by kmurica** [comment]
Maybe some kind of message box popup as well, with a progress bar would be a solution to this? For the really slow operations at least.
