### ISSUE TITLE
broker field in file writer command

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/nexus-constructor#612]
When you output a filewriter command there is a field to add a broker. Currently it is possible to leave this blank and it results in an empty string in the output json.
If the filewriter requires this field we should validate that something has been entered into the field. If it does not require a broker field in the message then not entering a value should instead result in the field not appearing at all in the output json.

**Comment by rerpha** [comment]
according to https://github.com/ess-dmsc/kafka-to-nexus/blob/master/documentation/commands.md

it is required, so we should make it a mandatory field.
