### ISSUE TITLE
ui_value is not generated when file is loaded

### ISSUE THREAD

**Issue by rerpha** [ess-dmsc/nexus-constructor#623]
transformation datasets with no value will need to be given the ui_value attribute and set to 0. When loading the bigfake.nxs file it does not load some of the transformations due to the lack of the attribute.

**Comment by rerpha** [comment]
blocked by #622 for now as the file does not load without this anyway.

**Comment by matthew-d-jones** [comment]
#622 fixed, so this ticket is no longer blocked
