### ISSUE TITLE
Warn user when deleting a linked transformation

### ISSUE THREAD

**Issue by rerpha** [ess-dmsc/nexus-constructor#644]
A user can currently delete a transformation that is linked to by another transformation without warning. 

We should at least warn the user about when this happens, perhaps with a [QMessageBox](https://doc.qt.io/qt-5/qmessagebox.html)

**Comment by kmurica** [comment]
Message box should contain a clear warning text and it should be possible for the user to **not** delete (i.e. OK and cancel buttons added to box).
