### ISSUE TITLE
Handle NXlogs as transformations

### ISSUE THREAD

**Issue by rerpha** [ess-dmsc/nexus-constructor#649]
Currently the `bigfake.nxs` file does not load properly due to `/entry/instrument/slit1/depends_on` which points to an `NXlog`.

It is falling over here: 

https://github.com/ess-dmsc/nexus-constructor/blob/b6559f088913e99d791152e263a1685fb4b08387/nexus_constructor/component/component.py#L170

**Comment by matthew-d-jones** [comment]
Might make sense to have a second `Transformation` class and make use of polymorphism.

**Comment by rerpha** [comment]
OK, seems like the problem with `slit1` is that it has multiple transformations, each of which depend on the previous transformation. For example, `/entry/instrument/slit1/depends_on` points to `transformations/x_offset`, which has a depends_on which points to `y_gap` seeing as they are in the same group.  `y_offset` points to `distance` which is the last in the chain.
