### ISSUE TITLE
Status message handling needs to be updated in the filewriter control window

### ISSUE THREAD

**Issue by rerpha** [ess-dmsc/nexus-constructor#654]
The pane on the left is not working correctly so we should update it to use the new status message format.

**Comment by rerpha** [comment]
I think we can simplify it and completely remove the list view, as only one file will be written at a time now!

**Comment by kmurica** [comment]
Might be closed without solution if we proceed on path in issue: https://github.com/ess-dmsc/nexus-constructor/issues/840

**Comment by zjttoefs** [comment]
Correct @kmurica !
