### ISSUE TITLE
Exceptions when a component with a transformation is deleted 

### ISSUE THREAD

**Issue by rerpha** [ess-dmsc/nexus-constructor#669]
To reproduce: 
1. Add a component 
2. Add a translation 
3. Delete the component (Not the translation itself but the actual component)
4. Add another component 
5. Add another transformation 

The transformation is not shown and the 3d view complains about a KeyError as it cannot find a component to apply the transformation to.

**Comment by SkyToGround** [comment]
Though I can not say for sure (and I will not be spending any time to figure this out), I think there is a high probability of this bug being fixed in the V20 branch. Then again, it might be that this bug has been re-introduced for the umpteenth time due to recent changes in the application.
