### ISSUE TITLE
Support reading colour information from OFF files

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/nexus-constructor#67]
OFF files can optionally contain colour information. This feature is used for McStas, so would be good to support here too.

(Requested by Torben 2018-12-12)

**Comment by ACLay** [comment]
Would this be just for the 3D visualisation in the GUI? Or should it be included in the nexus filewriter commands somwhere too?

**Comment by matthew-d-jones** [comment]
Just for visualisation
