### ISSUE TITLE
Mypy -> Found 290 errors in 61 files

### ISSUE THREAD

**Issue by mattclarke** [ess-dmsc/nexus-constructor#712]
One of the interviewees ran mypy against the code and it came back with  a number of errors. 
Theses should be investigated to see if they are actual errors and, if so, fixed.

**Comment by matthew-d-jones** [comment]
After configuring mypy, current output for model_change branch is
```
Found 182 errors in 26 files (checked 129 source files)
```

**Comment by kmurica** [comment]
Adding a link to mypy to this issue:
http://mypy-lang.org/
Neat tool!
