### ISSUE TITLE
Unclear which icons are greyed out

### ISSUE THREAD

**Issue by rerpha** [ess-dmsc/nexus-constructor#719]
They are all grey besides the delete button, so we should either add some colour or raise the buttons that are currently selectable.

**Comment by rerpha** [comment]
related to #720 as that also revolves around the icons being changed.

**Comment by kmurica** [comment]
If colors and icons are kept as is in https://github.com/ess-dmsc/nexus-constructor/issues/720 (i.e. grey), I believe simply raising the buttons should be a sufficient approach for the user to distinguish active and inactive buttons.

**Comment by ebadkamil** [comment]
Raising the button issue was already implemented  in #851 . However adding colors to buttons should remain as an open issue  as suggested by @matthew-d-jones . So not closing this issue as of now.
