### ISSUE TITLE
Icons are inconsistent and slightly unclear

### ISSUE THREAD

**Issue by rerpha** [ess-dmsc/nexus-constructor#720]
From the UI feedback at the ECP workshop, the icons are not that clear in indicating their purpose. 

They do have tooltips but could have labels instead? 
 
I think the "zoom" icon should have a plus and a picture of the lego brick like in the add/edit component buttons for starters. The "add link" button's icon could also be made clearer. 

The edit button could be made more clear by increasing the size of the spanner in the corner.

**Comment by kmurica** [comment]
This issue is related to the label visualization issue in https://github.com/ess-dmsc/nexus-constructor/issues/722
