### ISSUE TITLE
No visual indication of depends_on chain direction for transformations in UI

### ISSUE THREAD

**Issue by rerpha** [ess-dmsc/nexus-constructor#721]
Currently there is no way of seeing which order the `depends_on` chain is going for transformation. Tobias suggested we use a chain or somethign similar between the transformations and the component to see which order they go in as it's currently quite confusing and requires the user to know how nexus works and also try and infer the order from the 3d view.

**Comment by kmurica** [comment]
Before starting on this issue, confirm the solution design with Tobias Richter and team.
