### ISSUE TITLE
Add a "show button labels" option in a "view" menu

### ISSUE THREAD

**Issue by rerpha** [ess-dmsc/nexus-constructor#722]
We should add a view menu next to "file" containing a "show button labels" tickbox that shows the labels showing what the buttons are for above the component view.

**Comment by kmurica** [comment]
![image](https://user-images.githubusercontent.com/76992076/108848892-d49bbe00-75e1-11eb-91ea-8dc233c65b8d.png)

**Comment by matthew-d-jones** [comment]
Correct.
Tickets #719 and #720 are closely related. I think this ticket is really a suggestion for part of a solution for #720.
It would be worth looking at how other software deals with this situation (toolbar where it is difficult to convey the meaning of buttons with icons alone). Perhaps the ribbon in MS Office software provides some inspiration for how text and buttons can be used together to help?

**Comment by ebadkamil** [comment]
Thanks for the explanation Matt and Kenan. I am assigning this to myself to get started with `nexus_constructor`
