### ISSUE TITLE
Add fields to the treeview 

### ISSUE THREAD

**Issue by rerpha** [ess-dmsc/nexus-constructor#723]
Currently where the placeholder is above transformations we should show the list of widgets for a component so a user can edit them from the main window and not just the "edit component" window. 

This has been suggested by Jonas for a while, and the placeholder was there for this reason originally, but I don't think we had a ticket for it.

**Comment by kmurica** [comment]
Might be affected by decision how to proceed with https://github.com/ess-dmsc/nexus-constructor/issues/841
