### ISSUE TITLE
Get edit component functionality working with new model change

### ISSUE THREAD

**Issue by rerpha** [ess-dmsc/nexus-constructor#728]
Sub-ticket of #607 
Follows on from #695 
This might be easier if we turn it into a view at the same time (#496) but worth seeing if we can do it without changing anything first.

**Comment by rerpha** [comment]
I am going to do this next as its quite important to be able to edit a component as there is no other way of seeing what has been saved from the add component window!

**Comment by matthew-d-jones** [comment]
Done
