### ISSUE TITLE
Simplify code that generates 3d models

### ISSUE THREAD

**Issue by rerpha** [ess-dmsc/nexus-constructor#760]
This: 
https://github.com/ess-dmsc/nexus-constructor/blob/03f2a206b0ee670021473593291ddeed85b0887b/nexus_constructor/main_window.py#L241-L245

and This: 
https://github.com/ess-dmsc/nexus-constructor/blob/03f2a206b0ee670021473593291ddeed85b0887b/nexus_constructor/main_window.py#L253-L257

Don't really need to be separate if we are calling them whenever the model is updated anyway. I think we should just draw the components AND their respective translations any time something is changed.

**Comment by matthew-d-jones** [comment]
Realistically we won't get to this ticket (not a priority).
