### ISSUE TITLE
Remove non-standard json description

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/nexus-constructor#78]
We can currently output to our NeXus-json description compatible with the file writer, and another json description. The latter of these should be removed. It may be in use because the NeXus-json description is lossy, in which case may need to wait until we have a non-lossy save format (NeXus file?) before removing it.

See "JSON Formats" section of README, and make sure README is updated as part of this ticket.

**Comment by rerpha** [comment]
Blocked by #91

**Comment by rerpha** [comment]
No longer an issue in the widgets application so closing for now.
