### ISSUE TITLE
Add a PR Jenkins job to build the distributable on different platforms

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/nexus-constructor#81]
Windows, Mac and Linux distributables which should be downloadable as build artifacts after the Jenkins job is complete.

We don't have automated tests covering the interface itself, so this ticket is important to at least reduce the barrier to manual testing on different platforms.

**Comment by rerpha** [comment]
blocked by #97

**Comment by rerpha** [comment]
Might have a play around with PyInstaller instead of cx_freeze at some point and see if we can get the builds working on all platforms. cx_freeze seems to be including some paths that will never exist outside of jenkins and therefore the executables fail to run

**Comment by matthew-d-jones** [comment]
> Might have a play around with PyInstaller instead of cx_freeze at some point and see if we can get the builds working on all platforms. cx_freeze seems to be including some paths that will never exist outside of jenkins and therefore the executables fail to run

Alex originally looked into using PyInstaller, he encountered a couple of bugs with using it with pyside2, see https://github.com/ess-dmsc/nexus-constructor/issues/27
I think creating an appimage would be the the alternative approach to look into.
