### ISSUE TITLE
JSON loading: Pixel mapping for OFF Meshes

### ISSUE THREAD

**Issue by rerpha** [ess-dmsc/nexus-constructor#813]
Follows on from the work done in #807 

Cylinders are also not working, but aren't as important as meshes. 

documentation can be found [here](https://manual.nexusformat.org/classes/base_classes/NXoff_geometry.html) for guidance on how mapping OFFs work

**Comment by matthew-d-jones** [comment]
Branch is 803_pixel_mapping_json_loading (mistake in branch name)
