### ISSUE TITLE
Implement saving/loading JSON for transformations which are a KafkaStream

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/nexus-constructor#835]
Transformations can be an f142 KafkaStream which the filewriter creates an NXlog from. This is required when the transformation describes a motion axis which moves during an experiment for example. Currently this is not saved to or loaded from JSON by the NeXus Constructor.

**Comment by kmurica** [comment]
@ebadkamil mind doing this as a pair programming exercise next week maybe? It sounds interesting.

**Comment by ebadkamil** [comment]
yes. Let's do it.
