### ISSUE TITLE
Error dialog when loading JSON

### ISSUE THREAD

**Issue by mattclarke** [ess-dmsc/nexus-constructor#839]
When loading a file with a few cylindrical detectors I get a pop-up which says:
![image](https://user-images.githubusercontent.com/3032495/104312320-59b59280-54ce-11eb-8dc3-7cc50a84b134.png)

Can be reproduced by just creating a single cylindrical detector of height 1 and radius 1, then saving and reloading.

Note: despite the error, everything seems okay.

**Comment by kmurica** [comment]
Fixed and merged to main.
