### ISSUE TITLE
Decision/design treeview change

### ISSUE THREAD

**Issue by matthew-d-jones** [ess-dmsc/nexus-constructor#841]
The component treeview on the left side of the main window should show and allow editing of fields (datasets etc in the component). This change is requested by Tobias.
It could be addressed by a relatively small change of adding fields to the existing view (#723)
but it should be decided if the existing implementation should be replaced altogether, perhaps to introduce a full view of the file hierarchy like can be seen in tools like HDFView. It may be a factor in this decision that the current implementation is the most complex area of the codebase and would benefit from significant refactoring.

**Comment by kmurica** [comment]
I will try to get started with this issue after our next handover sync meeting on Friday (probably I can start on Monday).
I might need some inputs from you @matthew-d-jones and others in team how a redesign would best look like.
