### ISSUE TITLE
Create an AppImage or get cx_freeze working on linux 

### ISSUE THREAD

**Issue by rerpha** [ess-dmsc/nexus-constructor#97]

**Comment by matthew-d-jones** [comment]
The current distributable created on CentOS by cx_freeze doesn't execute on our Ubuntu 18.04 machines.

**Comment by probonopd** [comment]
Check out https://github.com/linuxdeploy/linuxdeploy-plugin-conda, it is an easy way to make a bundle that contains your application, Python and its libraries, and dependency Python modules. It can output an AppImage.
